language: node_js
sudo: false
node_js:
- 10
branch:
- master
install:
- npm install
script:
- mocha
deploy:
  provider: heroku
  api_key:
    secure: gtPh9Df3mMfbJoKcYndYrhF6BzjRtukaC/nqmcT/JYD+fyvyoUiQZUn7aprlyOUafnf1U9fd/8jYWTvQIc4+6hMJALl8BTsMgt3ro23fdoDgQr647kCtuaLtk7wjVMBmeXrag8g3ITUnGjKYoA9y7rRQRQwBSy14OgXdAFqWJkpRIV7vXMY3w8Vy4zwd0TozJt70HWVqu3p6/kzXglzcE558OUJQziRjPTFNcwQldI9sPhRb86lzAsL+pgOfJUr1SRZh5Viu6SSaX1/2Oi7Uy93xJVrWIi37taMyM9hUorm6SKqTeZyr0eu3Ilco+a9qs5ZvdNcFmBGVgFtw1RN004CoxMQ5AdHYl2eiK3QW25BbKr17XGWWoIxLCcfz4X7fwJLiaJQY7OP2fvtKjRYndUiKtYd5z/jJrIlSOUEZfRJxJbAT5JlbijTeyG/D87+hJ8bwAQVc+qAYXEPuXRF7qIUR0xod9zDttCnQC+2H+RBL1ahvdYA8po1LzbAL2FiJXNGS6+jvvOKohzdRSVmSAcRePvWPJyc9H2S4oPlMJTOteaComVu4oGJ3M6l4azfJo8TsQtvugIyoTMX8GTcOHCG7pUrXuEpSGoNwHfRYIq7guTqASPcprXecvC+lM8Cq1+xm8RgQE/uNHUq8Z7RzNIEgryhcivoBTVXtnBianjE=
  app: young-stream-38284
